spring:
  application:
    name: szs-application
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/refund-user-db;AUTO_SERVER=TRUE
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: "path-pattern-parser"

jwt:
  private-key: '{"p":"tvXtpGslqCARr7zd1-1Z0OpUBMBB_87YkUu78ajB32ATS55FZjz1c_h4zuQrlacS53I43ELq6KMcerIMZ93P4yPE_BtiIoadXO-woZttHtJEuBbtJS42H5Ab6r3O83G8KyciKXr0a-qEfFVjZOE6Jyd1Vhcxto719QMvjxV26lE","kty":"RSA","q":"2RN9sPYY2djGwyganU9zC_kFHip3sefIpqf8aCd6a46KGe6XBHqoJtYUFgfRHKtdV9OUpl03CCbDB9aetABvHeqgNSmoAhWpaIhYB9z9-vgzRVwbFTgF2kzaioVo1zsNVUojcoY4rtRFhr1dqbMqaxmfFimafXtxdwvuk6YyBF0","d":"An7M2rSzNzm3_j_huvuqq5lOj4P7Zmsmj0Q7LWMeu-W0-3dSjecl0xTAX_OSkZtRBGmSl9fHfd-0JNUkxPaCOBe9qDQQniH42dmjrFCXSL4-_epp8N5JyCN9rXQUNzHFsp0CSzxVdg_23MMoUxaokiLlk-SQJt5t0JGDCZiypoxMbzY49N14D7vvOeL2404V7tifEnIgC7z3Yer-d6TiWChtzLlK074RXqGxxi79zcxXrTZGxBJHecqCzmwFI8DSXsGlltooccd2EFG7n7sf_JJeNlUuCIYMQIWrLCjO86jyE7nCzbToOrhYDzFW6B5l-FshuGSzGkCS0pO7T0ltYQ","e":"AQAB","kid":"szs-application","qi":"Vu42mYZgsOVSOp0ThbtldTFiONEvBQXDfqP8KDQ9S50A1D2awU8oQb9LbwVVwNA_aIvfFScbyT5UG_wXp3ml7jUtQvae3RVRttUBOAm_kB3jUxRjlK2GzYN5yrnLMljmaKL7mlH45elQNOneGLJwnUGg70CWtf9VHDV2UO5vBRU","dp":"ptxfoYY-z7h_qOD9CkLjmQ89FSAqkRyaktiZTep09j3vGxX7gSSzTtMbisS5o0C-kuqvROKazxSDkrrzaX74a9Vhf_ORap-OwQWw95KC0ItANQxjt3cP0XVioJH_PjNKQ6jrFR2X8RvvPF27ynNG0BLChoOcyTxUwOHo6_vNeiE","dq":"b9vOWiEGf0NocOo6hLOLGjFRBNFnaoKA7_gCZf1p5QDHg0NiCInYGmMYaJ3QkNBxQi-iGvRPxmCLAYADuce7epQLyDlV_PUCnf4cNrkXG3tImEY1IoMC6RHPT7AdbUNdxIR2ra4iiVyTEzKDkE3l3tiOFNKNbHnu5yR75ROwFHU","n":"myRkhZAFncVguVJAkXkgurTGqnmB26fu6B_fwKMJscKTUCU2F2NWPzw4B17E9JT6FMlVUic7AP6et_becCwZZ1Pld0x7a-aXvr2n7WmSTtDYSGwvIpDzpRcmCvd-Cdtyjdtan1LdDSUdfWThoRXx3T0bdw97KaViblabEaPrIAbzLN3Vup-PvjfDHdipRnWvVcX3iK5_Cyw2iiSEhIYepPkKzkkutvVtH-A4p6-ob1_fSGoNoGkieILoAl9gGwyXgOJZlZuwXJ-3saPDfw9y_jYfR7QqZUhU7cYULGicCbSHCpM8I7B6Ey1J5odglXA513W7SUdCk4q6Xqr98a5jbQ"}'
  public-key: '{"keys":[{"kty":"RSA","e":"AQAB","kid":"szs-application","n":"myRkhZAFncVguVJAkXkgurTGqnmB26fu6B_fwKMJscKTUCU2F2NWPzw4B17E9JT6FMlVUic7AP6et_becCwZZ1Pld0x7a-aXvr2n7WmSTtDYSGwvIpDzpRcmCvd-Cdtyjdtan1LdDSUdfWThoRXx3T0bdw97KaViblabEaPrIAbzLN3Vup-PvjfDHdipRnWvVcX3iK5_Cyw2iiSEhIYepPkKzkkutvVtH-A4p6-ob1_fSGoNoGkieILoAl9gGwyXgOJZlZuwXJ-3saPDfw9y_jYfR7QqZUhU7cYULGicCbSHCpM8I7B6Ey1J5odglXA513W7SUdCk4q6Xqr98a5jbQ"}]}'
  access-expiration-time: 1800

scrap:
  host: "https://codetest.3o3.co.kr/v2/scrap"  # real server

server:
  port: 8080
